services:
  mysql:
    image: mysql:latest
    container_name: sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - mysql-network

volumes:
  mysql-data:

networks:
  mysql-network: