version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - mysql-network

  notesaverapi:
    image: notesaverapi
    container_name: notesaverapi-container
    build:
      context: .
      dockerfile: /Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./NoteSaverAPI.pfx:/root/.aspnet/https/NoteSaverAPI.pfx
    networks:
      - mysql-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8888

volumes:
  mysql-data:

networks:
  mysql-network: